import mongoose from "mongoose";

const workoutStrengthSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: "User",
      index: true,
    },
    date: { type: Date, default: Date.now },
    routineType: { type: String, required: [true, "Routine type is required"] },
    // Plan markers. Optional, and null for every session logged by a client that predates them.
    //
    // Without these a completed session is just a dated row: the coach hydrator has to GUESS
    // which planned day it was by counting how many sessions exist in the current week. With
    // them the link is exact, which is what lets the coach say what is left this week instead of
    // inferring it. `dayIndex` is the position within `weeks[].days`, matching the client's
    // workout_execution/{weekNumber}/{dayIndex} route.
    planId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "WorkoutPlan",
      default: null,
    },
    weekNumber: { type: Number, default: null, min: 1 },
    dayIndex: { type: Number, default: null, min: 0 },
    // An extra session the athlete added on top of the plan. It still carries the week and day it
    // was done on, but it never closes a plan day: the coach reads it as feedback only.
    isExtra: { type: Boolean, default: false },
    // Idempotency key, generated by the client when it starts a session. PUT
    // /api/workouts/strength/:clientId upserts on { userId, clientId }, so a retried sync or an
    // edit of a past workout updates one document instead of creating a duplicate. Absent on every
    // legacy log, hence the partial index below.
    clientId: { type: String },
    startedAt: { type: Date },
    durationSec: { type: Number, min: 0 },
    notes: { type: String, maxlength: 2000 },
    exercises: [
      {
        // The legacy fields below stay required and are derived by the client from `setLogs`, so
        // everything that reads a session (the coach's routine context) needs no change.
        exerciseName: { type: String, required: true },
        exerciseId: { type: String, default: null },
        notes: { type: String, maxlength: 1000 },
        sets: { type: Number, required: true },
        reps: { type: Number, required: true },
        targetWeight: { type: Number, required: true },
        actualWeight: { type: Number },
        targetRpe: { type: Number, required: true, min: 1, max: 10 },
        actualRpe: { type: Number, min: 1, max: 10 },
        // Per-set detail. Optional: a client that predates it sends none.
        setLogs: [
          {
            _id: false,
            type: {
              type: String,
              enum: ["normal", "warmup", "drop", "failure"],
              default: "normal",
            },
            weight: { type: Number, min: 0 },
            reps: { type: Number, min: 0 },
            targetReps: String,
            targetRpe: { type: Number, min: 1, max: 10 },
            actualRpe: { type: Number, min: 1, max: 10 },
          },
        ],
      },
    ],
  },
  { timestamps: true },
);

// Unique per athlete, and only for logs that carry a clientId: legacy documents have none, and a
// plain unique index would treat every missing value as the same key.
workoutStrengthSchema.index(
  { userId: 1, clientId: 1 },
  { unique: true, partialFilterExpression: { clientId: { $type: "string" } } },
);

export default mongoose.model("WorkoutStrength", workoutStrengthSchema);
